name = "JutulDarcyRules-example"
authors = ["Ziyi Yin"]

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JOLI = "bb331ad6-a1cf-11e9-23da-9bcb53c69f6f"
JUDI = "f3b833dc-6b2e-5b9c-b940-873ed6319979"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SlimPlotting = "f6d04670-764e-495b-a720-91c3c9a588ff"
